### PR TITLE
Add Arlen lt patches

### PR DESCRIPTION
**Pull request by Wolf3s**
See the commits for more informations.

### CODE REVIEW

**Comment by Wolf3s** [comment]
@sahlberg the PR is ready to go.

**Comment by Wolf3s** [comment]
Note: there's function which is:
void SMB2APIENTRY smb2_set_version(struct smb2_context *smb2,
                      enum smb2_negotiate_version version)
{
    smb2->version = version;
}

and arlen lt has added:
void SMB2APIENTRY smb2_set_negotiate_version(struct smb2_context* smb2, enum smb2_negotiate_version version)
{
    smb2->version = version;
}

Which is the same of the other one, However i kept the other one for backwards compatibility maybe in the next-gen smb2 this one should be removed.

**Comment by sahlberg** [comment]
Can you update this and resolve the conflicts?

**Comment by Wolf3s** [comment]
> Can you update this and resolve the conflicts?

Yes, when i return 2 weeks later.

**Comment by Wolf3s** [comment]
@sahlberg i solved the conflict you can merge now.

**Pull request closed without merging**
