### PR TITLE
ps2: Add missing HAVE_TIME_H and add HAVE_FCNTL_H

### PR DESCRIPTION
**Pull request by Wolf3s**

### CODE REVIEW

**Comment by sahlberg** [comment]
Merged, thanks.

Maybe we should add a makefile and compatibility code to build on IOP as well like libnfs does.

**Comment by Wolf3s** [comment]
> Merged, thanks.
> 
> Maybe we should add a makefile and compatibility code to build on IOP as well like libnfs does.

Libnfs if not mistaken does not support iop

**Comment by sahlberg** [comment]
Ah, sorry, you are right. I only added IOP support to libsmb2. I mixed them up.

Long time ago I had a prototype IRX for smb2  but it would hang after a short wile doing I/O and I never got around to manage to debug it :-(
It would be nice to maybe resurrect it and give it a new try during the upcoming holidays or something.

**Comment by sahlberg** [comment]
I mentioned I had a prototype smb2 irx but I never got it to be stable. It would work for a while and eventually hang and debugging iop code is hard.

If you want to test it out, here it is :
https://github.com/sahlberg/ps2sdk/tree/smb2man

If you want to have a look or maybe get it to work reliably or take it over, please have a look.

**Comment by Wolf3s** [comment]
> I mentioned I had a prototype smb2 irx but I never got it to be stable. It would work for a while and eventually hang and debugging iop code is hard.
> 
> If you want to test it out, here it is : https://github.com/sahlberg/ps2sdk/tree/smb2man
> 
> If you want to have a look or maybe get it to work reliably or take it over, please have a look.

I will see but creating a separate module for ps2sdk is not a good idea since it exists a library that performs exact the same thing. It could be easier merge here then go to ps2sdk.

**Comment by Wolf3s** [comment]
https://github.com/Wolf3s/wLaunchELF/tree/SMB2

**Comment by sahlberg** [comment]
Interesting. I haven't looked at this in very long. And to be honest, I didn't know much what I was doing being completely new and unfamiliar with PS2 programming. I somehow mananaged to get it to work by butchering parts and moving lwip onto EE.

Your version here runs libsmb2 on EE but LWIP on IOP?   And you don't have to break things like I did?

That would be awesome.   Do you want to take on the maintenance of wLE with smb2/nfs support?
I can replace my github repo and just have a README that re-directs to your stuff if you want to.
SMB2 and NFS is very useful to have and it deserves to be maintained by someone that know what they are doing (i.e. not me:-) )

**Comment by Wolf3s** [comment]
> Interesting. I haven't looked at this in very long. And to be honest, I didn't know much what I was doing being completely new and unfamiliar with PS2 programming. I somehow mananaged to get it to work by butchering parts and moving lwip onto EE.
> 
> Your version here runs libsmb2 on EE but LWIP on IOP? And you don't have to break things like I did?
> 
> That would be awesome. Do you want to take on the maintenance of wLE with smb2/nfs support? I can replace my github repo and just have a README that re-directs to your stuff if you want to. SMB2 and NFS is very useful to have and it deserves to be maintained by someone that know what they are doing (i.e. not me:-) )
 
I didn't break nothing also ps2sdk now has contantly updated with new features that brome your port.

**Comment by Wolf3s** [comment]
> I mentioned I had a prototype smb2 irx but I never got it to be stable. It would work for a while and eventually hang and debugging iop code is hard.
> 
> If you want to test it out, here it is : https://github.com/sahlberg/ps2sdk/tree/smb2man
> 
> If you want to have a look or maybe get it to work reliably or take it over, please have a look.

New place of smb2man: https://github.com/Wolf3s/ps2sdk/tree/smb/iop/network/smb2man

**Comment by sahlberg** [comment]
Nice

**Pull request merged**
