### PR TITLE
Check for time.h and include as appropriate

### PR DESCRIPTION
**Pull request by SeanMcG**
musl libc defines time_t in this header

### CODE REVIEW

**Comment by Wolf3s** [comment]
@SeanMcG You should add these for the makefiles

**Comment by SeanMcG** [comment]
> @SeanMcG You should add these for the makefiles

I'm not sure I understand, can you elaborate?

**Comment by sahlberg** [comment]
This looks good.

**Comment by sahlberg** [comment]
merged, thanks

**Pull request merged**
