### PR TITLE
Support Clang/Xcode and support Kerberos on macOS

### PR DESCRIPTION
**Pull request by amosavian**
This pull request adds module.modulemap to allow clang to treat this library as
a framework, allowing use of "`import`" rather than include and provides better
support for Swift binding.

Also krb5wrapper has been modified to support macOS.
I've disabled a section of code as `gss_set_neg_mechs()` is not defined on macOS.

Please note I've changed two cases of angled-bracket include to double-quoted one
as it did not compile on my computer. **I hope it won't break anything on other systems.**

### CODE REVIEW

**Comment by Wolf3s** [comment]
> This pull request adds module.modulemap to allow clang to treat this library as a framework, allowing use of "`import`" rather than include and provides better support for Swift binding.
> 
> Also krb5wrapper has been modified to support macOS. I've disabled a section of code as `gss_set_neg_mechs()` is not defined on macOS.
> 
> Please note I've changed two cases of angled-bracket include to double-quoted one as it did not compile on my computer. **I hope it won't break anything on other systems.**

Hey there, could you try to merge to the latest branch?

**Comment by amosavian** [comment]
@Wolf3s Would you mind checking again?

**Comment by Wolf3s** [comment]
> @Wolf3s Would you mind checking again?

Yeah

**Comment by Wolf3s** [comment]
@amosavian https://github.com/amosavian/libsmb2/pull/1

**Comment by Wolf3s** [comment]
It works pretty well now, i think @sahlberg would merge this one.

**Comment by sahlberg** [comment]
It needs some more changes.
The include files that are installed into /usr/include/smb2 should not change to use #include "" to include the other files that also end up in /usr/include/smb2.   They should continue to use #include <>

**Comment by Wolf3s** [comment]
> It needs some more changes. The include files that are installed into /usr/include/smb2 should not change to use #include "" to include the other files that also end up in /usr/include/smb2. They should continue to use #include <>

i´ve added #include <> it should work on mac os normally.

**Comment by amosavian** [comment]
When I use Swift Package Manager, so no headers would be found on `/usr/include/smb2` and I don't know how to resolve this issue. @sahlberg

**Comment by amosavian** [comment]
I will close and reopen another PR in order to change source branch @Wolf3s @sahlberg

**Pull request closed without merging**
