### PR TITLE
Migration and Cleanup: Move PICO_BOARD and ESP_PLATFORM to cmake

### PR DESCRIPTION
**Pull request by Wolf3s**
~~* Move autotools build to CMake.~~
* Support autotools functions in CMake.
* Cleanup smb2man folder with CMakeLists.txt
* Improve GSSAPI and libkrb5 detection.

### CODE REVIEW

**Comment by sahlberg** [comment]
The other changes look fine   but don't remove autotools.

**Comment by Wolf3s** [comment]
> The other changes look fine but don't remove autotools.

I will restore autotools build

**Comment by Wolf3s** [comment]
@sahlberg

**Comment by sahlberg** [comment]
Merged, thanks

**Pull request merged**
