### PR TITLE
Add ee on iop stack 

### PR DESCRIPTION
**Pull request by Wolf3s**
Based on: https://github.com/sahlberg/libsmb2/commit/16c0a8c5231b3a887570d5ce819e38f1fb62fe66

### CODE REVIEW

**Comment by sahlberg** [comment]
Looks good. I am happy to merge once you remove the Draft  tag.

**Comment by Wolf3s** [comment]
> Looks good. I am happy to merge once you remove the Draft tag.

yep but this one specific is kind weirdo since it mixes two processors in one.

**Comment by Wolf3s** [comment]
Anyway there´s more pull requests to come, related to other platforms.

**Comment by Wolf3s** [comment]
> requests



> There´s a copule pull requests to come, related to other platforms after this one.

update: i really tested and it´s working however it needs the ps2ips.irx to work + init the ps2ips library itself. More work should needed.

**Comment by Wolf3s** [comment]
I will remove the draft tag.

**Pull request merged**
